name: Deploy storybooks to GitHub Pages

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment: gh-pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 19

      - name: Install dependencies
        run: pnpm install